{% set name = "pandas-alive" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pandas_alive/pandas_alive-{{ version }}.tar.gz
  sha256: dae14ba8af869c6a9f91e40709d63216d93dda2d7674e9223a347821ae6cb986

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
   host:
      - poetry >=0.12
      - pip
      - python >=3.6.1,<4.0.0
   run: 
      - python >=3.6.1,<4.0.0
      - pandas >=1.0.3,<2.0.0
      - matplotlib-base >=3.2.1,<4.0.0
      - attrs  >=19.3.0,<20.0.0
      - pillow >=7.1.2,<8.0.0

test:
  imports:
    - pandas_alive

about:
  home: https://github.com/JackMcKew/pandas_alive
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Animated plotting extension for Pandas with Matplotlib'

  description: |
    Pandas_Alive is intended to provide a plotting backend for animated matplotlib
    charts for Pandas DataFrames, similar to the already existing Visualization 
    feature of Pandas. With Pandas_Alive, creating stunning, animated visualisations
    is as easy as calling: df.plot_animated()

  doc_url: https://jackmckew.github.io/pandas_alive/
  dev_url: https://github.com/JackMcKew/pandas_alive

extra:
  recipe-maintainers:
    - JackMcKew
    - owenlamont
